spring:
  datasource:
    primary:
      platform: h2
      driverClassName: org.h2.Driver
      url: jdbc:h2:file:./db/primary
      username: sa
      password:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show_sql: false
        hibernate:
          ddl-auto: none
        component-scans:
          com.example.domain.model
    secondary:
      platform: h2
      driverClassName: org.h2.Driver
      url: jdbc:h2:file:./db/secondary
      username: sa
      password:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show_sql: false
        hibernate:
          ddl-auto: none
        component-scans:
          com.example.domain.model
